const state={players:[],filter:'ALL',lineup:loadLineup(),activePointers:new Map()};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const slots=['PG','SG','SF','PF','C'];

function loadLineup(){try{return JSON.parse(localStorage.getItem('nba-card-lineup'))||{}}catch{return {}}}
function saveLineup(){localStorage.setItem('nba-card-lineup',JSON.stringify(state.lineup))}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function positionText(p){return p.positions.map((x,i)=>`${x} ${p.positionsZh[i]}`).join(' / ')}
function playerById(id){return state.players.find(p=>p.id===id)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}

function cardVisual(p,detail=false){return `<div class="tilt-card" data-tilt data-id="${p.id}" style="--accent:${p.accent};--accent2:${p.accent2}"><img src="${detail?p.assets.front:p.assets.thumb}" alt="${esc(p.name)} 球星卡" draggable="false"><span class="foil-layer"></span><span class="glare-layer"></span></div>`}

function renderHero(){const picks=[state.players[1],state.players[3],state.players[0]].filter(Boolean);$('#hero-stack').innerHTML=picks.map(p=>`<div class="hero-card" style="background-image:url('${p.assets.thumb}')"></div>`).join('');$('#card-count').textContent=String(state.players.length).padStart(2,'0')}

function renderGallery(){const list=state.filter==='ALL'?state.players:state.players.filter(p=>p.positions.includes(state.filter));$('#card-grid').innerHTML=list.map(p=>`<article class="gallery-card" data-player="${p.id}">${cardVisual(p)}<div class="card-meta"><div><h3>${esc(p.name)}</h3><p>${positionText(p)} · ${p.teamShort}</p></div><span class="rating">${p.rating}</span></div><div class="card-actions"><button data-detail="${p.id}">查看卡面</button><button data-add="${p.id}">加入阵容</button></div></article>`).join('')||'<p>该位置暂无球员。</p>';setupTilts($('#card-grid'))}

function setupTilts(root=document){root.querySelectorAll('[data-tilt]').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound='1';let dragging=false,raf=0,px=50,py=50;
 el.addEventListener('pointerdown',e=>{dragging=true;el.setPointerCapture(e.pointerId)});
 el.addEventListener('pointermove',e=>{if(!dragging&&e.pointerType!=='mouse')return;const r=el.getBoundingClientRect();px=(e.clientX-r.left)/r.width*100;py=(e.clientY-r.top)/r.height*100;if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const rx=(50-py)*.12,ry=(px-50)*.14;el.style.transform=`perspective(900px) rotateX(${rx}deg) rotateY(${ry}deg) scale3d(1.018,1.018,1.018)`;el.style.setProperty('--px',px+'%');el.style.setProperty('--py',py+'%');el.style.setProperty('--mx',(px-50)*.8+'px');el.style.setProperty('--my',(py-50)*.8+'px')})});
 const reset=()=>{dragging=false;el.style.transform='';el.style.setProperty('--px','50%');el.style.setProperty('--py','50%')};el.addEventListener('pointerup',reset);el.addEventListener('pointercancel',reset);el.addEventListener('pointerleave',reset)});}

function openDetail(id){const p=playerById(id);if(!p)return;const stats=Object.entries(p.stats).map(([k,v])=>`<div class="stat-row"><span>${({finishing:'终结',shooting:'投射',playmaking:'组织',defense:'防守'})[k]}</span><span class="stat-bar"><i style="width:${v}%"></i></span><b>${v}</b></div>`).join('');$('#detail-content').innerHTML=`<div class="detail-layout"><div class="detail-visual">${cardVisual(p,true)}</div><div class="detail-copy"><p class="kicker"><span></span>${p.rarity} · OVR ${p.rating}</p><h2>${esc(p.name)}<i>${esc(p.title)}</i></h2><div class="position-chips">${p.positions.map((x,i)=>`<span>${x} ${p.positionsZh[i]}</span>`).join('')}</div><div class="stats">${stats}</div><button class="cta wide" data-add="${p.id}">加入首发 <b>＋</b></button>${p.id==='lebron-james'?'<a class="ghost legacy-link" href="/legacy/lebron/" target="_blank">打开完整 3D 卡 ↗</a>':''}<p class="source-note">图片：${esc(p.sourceCredit)}<br><a href="${p.sourceUrl}" target="_blank" rel="noreferrer">查看素材来源</a></p></div></div>`;setupTilts($('#detail-content'));$('#card-dialog').showModal()}

function addToLineup(id,preferred){const p=playerById(id);if(!p)return;const occupied=Object.entries(state.lineup).find(([,v])=>v===id);if(occupied){toast(`${p.name} 已在 ${occupied[0]} 位置`);return}const choices=preferred&&p.positions.includes(preferred)?[preferred]:p.positions;const target=choices.find(pos=>!state.lineup[pos]);if(target){state.lineup[target]=id;saveLineup();renderLineup();toast(`${p.name} 已进入 ${target} 首发`);return}const targetNames=p.positions.map(x=>`${x} ${p.positionsZh[p.positions.indexOf(x)]}`).join(' / ');toast(`${targetNames} 均已有人，请先移除一位球员`)}

function renderLineup(){slots.forEach(pos=>{const slot=$(`[data-slot="${pos}"]`);const p=playerById(state.lineup[pos]);slot.innerHTML=p?`<div class="slot-player" style="background-image:url('${p.assets.thumb}')"><span>${esc(p.name)}</span></div><button class="slot-remove" data-remove="${pos}" aria-label="移除 ${esc(p.name)}">×</button>`:''});const team=slots.map(s=>playerById(state.lineup[s])).filter(Boolean);$('#team-rating').textContent=team.length?Math.round(team.reduce((n,p)=>n+p.rating,0)/team.length):'--'}

function drawPlayer(){const dialog=$('#draw-dialog'),content=$('#draw-content');content.innerHTML='<div class="draw-stage"><div class="pack">CARD<br>ARENA<small>CLICK TO RIP</small></div></div>';dialog.showModal();const pack=content.querySelector('.pack');pack.onclick=()=>{pack.style.animation='none';pack.textContent='OPENING';setTimeout(()=>{const p=state.players[Math.floor(Math.random()*state.players.length)];content.innerHTML=`<div class="draw-stage"><div class="draw-result"><img src="${p.assets.front}" alt="抽到 ${esc(p.name)}"><h2>${esc(p.name)}</h2><p>${positionText(p)} · OVR ${p.rating}</p><button class="cta" data-add="${p.id}">加入阵容 <b>＋</b></button></div></div>`},680)}}

function bind(){document.addEventListener('click',e=>{const detail=e.target.closest('[data-detail]');if(detail)openDetail(detail.dataset.detail);const add=e.target.closest('[data-add]');if(add)addToLineup(add.dataset.add);const remove=e.target.closest('[data-remove]');if(remove){delete state.lineup[remove.dataset.remove];saveLineup();renderLineup()}if(e.target.closest('[data-action="draw"]'))drawPlayer()});$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-position]');if(!b)return;state.filter=b.dataset.position;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));renderGallery()});$('#reset-lineup').onclick=()=>{state.lineup={};saveLineup();renderLineup()};$$('dialog .dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}))}

async function init(){try{const data=await fetch('/cards/manifest.json').then(r=>{if(!r.ok)throw Error('球星卡清单加载失败');return r.json()});state.players=data.players;renderHero();renderGallery();renderLineup();bind()}catch(e){console.error(e);$('#card-grid').innerHTML=`<p>${esc(e.message)}。请先运行 npm run build:cards。</p>`}}
init();
